--- Makefile	2021-10-27 12:07:50.890050000 +0200
+++ Makefile_patched	2021-10-26 16:15:56.183943000 +0200
@@ -124,3 +124,4 @@
 obj-$(CONFIG_ARCH_ZX)			+= zte/
 obj-$(CONFIG_ARCH_ZYNQ)			+= zynq/
 obj-$(CONFIG_COMMON_CLK_ZYNQMP)         += zynqmp/
+obj-$(CONFIG_GEM5_CPUFREQ_CLK)		+= gem5/
